target-version = "py311"
line-length = 88

[lint]
select = ["E", "F", "W", "I", "UP", "N", "B", "A", "C4", "PT", "RUF"]
ignore = ["RUF012"]

[lint.per-file-ignores]
"*/migrations/*.py" = ["E501", "N806"]
"*/tests/*.py" = ["N802"]
"scripts/*.py" = ["E402"]
