# Generated by Django 5.2.12 on 2026-05-06 18:16

import django.db.models.deletion
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
            options={
                "ordering": ["-start_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="core_event_end_time_after_start_time",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_path", models.CharField(max_length=1024)),
                (
                    "duration_limit",
                    models.PositiveIntegerField(help_text="Duration limit in seconds."),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="core.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        default=apps.core.models.generate_access_token,
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_duration",
                    models.PositiveIntegerField(
                        help_text="Maximum duration in seconds."
                    ),
                ),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="core.content",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="core_access_token_idx"),
                    models.Index(
                        fields=["expires_at"], name="core_access_expires_at_idx"
                    ),
                    models.Index(fields=["is_revoked"], name="core_access_revoked_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["event"], name="core_content_event_idx"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["file_path"], name="core_content_file_path_idx"),
        ),
    ]
