# Generated by Django 5.2.14 on 2026-05-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="cover",
            field=models.ImageField(
                blank=True,
                help_text="Preview image shown on the public catalog.",
                null=True,
                upload_to="covers/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Price in IDR (e.g. 4500000 for Rp 4.500.000).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="title",
            field=models.CharField(
                blank=True, help_text="Display name, e.g. 'FOTO+VIDEO'.", max_length=255
            ),
        ),
    ]
