# Generated by Django 5.2.14 on 2026-05-07 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_content_cover_content_price_content_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="requested_content",
        ),
    ]
