# Generated by Django 5.2.14 on 2026-05-07 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_order_requested_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="core.content",
            ),
        ),
    ]
